export const PARENTS_INFO_CONTENT = {
  GROOM_DAD_PREFIX: 'PUTRA DARI BAPAK',
  GROOM_DAD_NAME: 'YEO KHEE YONG',
  GROOM_MOM_PREFIX: 'DAN IBU',
  GROOM_MOM_NAME: 'PEK KIM LING',
  BRIDE_DAD_PREFIX: 'PUTRI DARI BAPAK',
  BRIDE_DAD_NAME: 'HERMAN (ALM)',
  BRIDE_MOM_PREFIX: 'DAN IBU',
  BRIDE_MOM_NAME: 'RAJA NOOR SYAM DEWI',
  WELCOME_MESSAGE: 'yang Insya Allah akan dilaksanakan pada:'
};